### ISSUE TITLE
Files in docs_dir being copied to nested dir

### ISSUE THREAD

**Issue by dumplinginsoda** [athackst/mkdocs-simple-plugin#57]
Thank you for building such a useful plugin :)

I've run into some issue with files in `docs` directory being copied incorrectly.

The setup I'm using is:

mac os,
python 3.8.5
mkdocs 1.1.2
mkdocs_simple_plugin 0.1.8

My repo structure looks like:

```
├── charts
  ├── chart A
    └── README.md
  └── chart B
    └── README.md
├── docs
  ├── index.md
  └── FAQ.md
└── mkdocs.yaml
```

mkdocs.yaml:
```
site_name: foo

theme:
  name: material
plugins:
  - simple:
      include_folders:
        - "./charts/*"

docs_dir: docs
use_directory_urls: false

nav:
  - About: index.md
  - Charts:
    - chart A: charts/chart A/README.md
    - chart B: charts/chart B/README.md
  - FAQ: FAQ.md
```

While reading through the code, I noticed [this specific line](https://github.com/athackst/mkdocs-simple-plugin/blob/master/mkdocs_simple_plugin/plugin.py#L65) is related to the issue I'm seeing. Is this an intended behavior?

**Comment by dumplinginsoda** [comment]
For now, I'm able to have everything working with `mkdocs_simple_plugin@v0.0.6`.

**Comment by athackst** [comment]
Yeah, it's intended. I was having issues with merging docs and all other documentation together in the same folder becuase

1) I found that relative links for files from/to the docs directory didn't work with a pure merge.  :cry:
2) Files could get overwritten if they had the same name

(1) is fixable, but (2) isn't really. So I changed it so that if the directory was "mixed" with items in the docs dir and elsewhere, it would just use the same folder structure as the source.  This is how the rest of the markdown files are incorporated into the site build and it seemed like the most intuitive solution.

Could you change your structure to the following and update your include line?

```
├── charts
  ├── chart A
    └── README.md
  └── chart B
    └── README.md
├── index.md
├── FAQ.md
└── mkdocs.yaml
```

**Comment by oncleben31** [comment]
I think I have a related issue.
I have in my docs dir a CNAME file which seems to not be copied in the /site folder with `mkdocs build` command.

Do you have any idea how to configure the project with your plugin to make it work.

**Comment by oncleben31** [comment]
To clarify my setup:
```
├── docs
  ├── CNAME
├── README.md
└── mkdocs.yaml
```

**Comment by athackst** [comment]
You should be able to include CNAME in the top level

```
├── CNAME
├── README.md
└── mkdocs.yaml
```

and then configure 

```
plugins:
  - simple:
      include_extensions: ["CNAME"]
```

But I can see how the default mkdocs setup doesn't quite work with my assumption on mixed setups.

I can make merging with the docs directory configurable.

**Comment by athackst** [comment]
Ok.  I added an extra config option to address this issue.  By default, it will merge the docs together instead of maintaining 'docs' as a separate folder, so you shouldn't have to make any configuration changes.

```
      # Optional setting to specify if the docs directory should be merged with other documentation
      merge_docs_dir: True
```

Please update to v0.2

**Comment by oncleben31** [comment]
Tested. OK Thank you for the quick answer.
